// Welcome!
// Add your github user if you accepted the challenge!

var players = [
    'raphamorim',
    'israelst',
    'afonsopacifer',
    'rafaelfragosom',
    'brunokinoshita',
    'paulinhoerry',
    'enieber',
    'alanrsoares',
    'viniciusdacal',
    'thiagosantana',
    'brunodsgn',
    'danilorb',
    'douglasPinheiro',
    'michelwilhelm',
    'joaovsilva',
    'rafaelstz',
    'andersonweb',
    'luhad',
    'pablobfonseca',
    'willianjusten',
    'vitorleal',
    'IAMFELIPEMATTOS',
    'JulianSansat',
    'brenopolanski',
    'Pompeu',
    'filipedeschamps',
    'felipesousa',
    'gpedro',
    'leaofelipe',
    'wedneyyuri',
    'jonathanveg',
    'filipe1309',
    'afgoulart',
    'helquisson',
    'vulcanobr',
    'guilouro',
    'pedropolisenso',
    'jozadaquebatista',
    'alfv89',
    'jugoncalves',
    'guilhermeepaixaoo',
    'morvanabonin',
    'andrecgro',
    'thulioph',
    'lucasviola',
    'iceberg20',
    'hugolnx',
];

module.exports = players;
